version: '2'

services:
  api:
    image: node:8.1.2
    command: bash -c "cd /workdir && npm run api"
    volumes:
      - ./:/workdir
    networks:
      - back-tier
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

networks:
  back-tier:
